#!/bin/sh

# launch the keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# lauch the polybar 
$XDG_CONFIG_HOME/polybar/launch.sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

num=$(xrandr --listmonitors | awk -F '[/| |+]+' '/^[^M]/ {print $7}' | uniq | wc -l)

if [[ $num -eq 1 ]]; then
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
else
    bspc monitor eDP-1 -d I III V VII IX 
    bspc monitor HDMI-1 -d II IV VI VIII X
fi


bspc config border_width         2
bspc config window_gap           4 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
